sudo: required
language: node_js
node_js:
  - "6.12"
script: cd server && npm install && npm test

services:
  - docker

after_deploy:
  - echo "done deploying"

deploy:
  - provider: elasticbeanstalk
    before_deploy:
      pip install --user awscli
      git subtree split --prefix=server -b release-server
      git checkout release-server
      aws s3 cp s3://tw-config/config.js ./config/config.js --region ap-northeast-2
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: "$AWS_SECRET_ACCESS_KEY"
    region: "us-east-1"
    app: "tw-service"
    env: "tw-test2"
    bucket_name: "elasticbeanstalk-us-east-1-141248341265"
    on:
      branch: master
