import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {normalizeWeather,DEFAULT_UNITS} from '/root/.paseo/worktrees/08mqediz/shiny-elephant/packages/weather-core/src/index.ts';
import {validateSnapshot,weatherKey} from '/root/.paseo/worktrees/08mqediz/shiny-elephant/web/src/state.ts';
const root='/root/.paseo/worktrees/08mqediz/shiny-elephant/';
const seed=JSON.parse(readFileSync(root+'docs/rewrite/examples/client-kma-response.json','utf8')).response;
const checks=[];
const raw=structuredClone(seed);
raw.short=[{date:'20261231',time:24,t3h:0,skyIcon:'sun',wsd:3,wdd:'NW',r06:6,s06:2,weather:'fallback',pop:70,reh:77}];
raw.shortest=[{date:'20270101',time:'0000',t1h:-50,rn1:-1,sn1:0,wsd:-1,wdd:'',skyIcon:'',weather:'',pop:0}];
let w=normalizeWeather(raw);
assert.equal(w.hourly.length,1);
assert.deepEqual(Object.fromEntries(['at','temperature','icon','wind','windDirection','precipitation','precipitationHours','snowfall','snowfallHours','description','rainProbability','humidity'].map(k=>[k,w.hourly[0][k]])),{at:'2027-01-01T00:00',temperature:0,icon:'sun',wind:3,windDirection:'NW',precipitation:6,precipitationHours:3,snowfall:0,snowfallHours:1,description:'fallback',rainProbability:0,humidity:77});
checks.push('year rollover collision: zero retained, sentinel/string/default-icon cannot erase fallback, snow1h and rain3h stay paired');
raw.short=[];raw.shortest=[{date:'20270101',time:'0230',t1h:2,rn1:0},{date:'20270101',time:'0100',t1h:1,rn1:-1},{date:'20270101',time:'0200',t1h:0,sn1:0},{date:'20270230',time:'0200',t1h:99}];
w=normalizeWeather(raw);assert.deepEqual(w.hourly.map(p=>p.at.slice(-5)),['01:00','02:00','02:30']);assert.equal(w.hourly[0].precipitation,null);assert.equal(w.hourly[2].precipitation,0);
checks.push('shortest-only feed survives absent short data; minute ordering and invalid date filtering hold');
const reordered=normalizeWeather({...raw,shortest:[...raw.shortest].reverse()});assert.deepEqual(w.hourly,reordered.hourly);checks.push('distinct-timestamp input ordering does not change merged forecast');
raw.airInfoList=[];raw.current.summaryAir='  <img src=x onerror=alert(1)> 공급사 요약  ';w=normalizeWeather(raw);assert.equal(w.airSummary,'<img src=x onerror=alert(1)> 공급사 요약');assert.equal(w.air.length,0);assert.equal(w.availability.air,'unavailable');
const key=weatherKey(w.location,w.units),now=Date.now();
assert.ok(validateSnapshot({weather:w,savedAt:now},key,now));
for(const val of [null,[],{},false,0,'','\t\n','a'.repeat(501)]) assert.equal(validateSnapshot({weather:{...w,airSummary:val},savedAt:now},key,now),undefined);
assert.ok(validateSnapshot({weather:{...w,airSummary:'a'.repeat(500)},savedAt:now},key,now));
const old={...w};delete old.airSummary;assert.ok(validateSnapshot({weather:old,savedAt:now},key,now));
assert.equal(validateSnapshot({weather:w,savedAt:now-86400001},key,now),undefined);
checks.push('summary plain text preserves unavailable numeric air; snapshot accepts 500-char/old records and rejects invalid shapes, whitespace, overlimit and expired records');
console.log(JSON.stringify({status:'passed',checks},null,2));
